version: '3.3'

services:

  eureka:
    image: registry.cn-qingdao.aliyuncs.com/upcwangying/samples-eureka:0.1.0-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "8762:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080

  admin:
    image: registry.cn-qingdao.aliyuncs.com/upcwangying/samples-admin:0.1.1-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9093:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080

  hystrix-dashboard:
    image: registry.cn-qingdao.aliyuncs.com/upcwangying/samples-hystrix-dashboard:0.1.0-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9094:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8080

  zuul:
    image: registry.cn-qingdao.aliyuncs.com/upcwangying/samples-zuul:0.1.1-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9090:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8080
    depends_on:
      - eureka
      - user

  user:
    image: registry.cn-qingdao.aliyuncs.com/upcwangying/user-server:0.1.3-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9095:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8080
      ADMIN_HOST: 'admin'
      ADMIN_PORT: 8080
    depends_on:
      - eureka
      - admin

  product:
    image: registry.cn-qingdao.aliyuncs.com/upcwangying/product-server:0.1.3-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9092:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8080
      ADMIN_HOST: 'admin'
      ADMIN_PORT: 8080
    depends_on:
      - eureka
      - admin

  order:
    image: registry.cn-qingdao.aliyuncs.com/upcwangying/order-server:0.1.3-SNAPSHOT
    restart: on-failure
    networks:
      - samples
    ports:
      - "9091:8080"
    environment:
      JAVA_OPTS: '-server -Xmx1g'
      PROFILE: 'default'
      SERVER_PORT: 8080
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8080
      ADMIN_HOST: 'admin'
      ADMIN_PORT: 8080
    depends_on:
      - eureka
      - admin

networks:
  samples:

volumes:
  mydata:
